<!-- Footer -->
	<div id="footer">
		<div class="container">
			<div class="row">
				<section class="3u 6u(narrower) 12u$(mobilep)">
					<h3>Links</h3>
					<ul class="links">
						<li><a href="index.html">Home Page</a></li>
						<li><a href="mission.html">Our Mission</a></li>
						<li><a href="documents.html">Documents</a></li>
						<li><a href="contact.html">Contact Us</a></li>

					</ul>
				</section>
				<section class="3u 6u$(narrower) 12u$(mobilep)">
					<h3>Services</h3>
					<ul class="links">
						<li><a href="compliance">Compliance Intiatives</a></li>
						<li><a href="regulatory-audit.html">Regulatory Auditing</a></li>
						<li><a href="vendor-assessment.html">Vendor Assessment</a></li>
						<li><a href="reporting.html">Advanced Reporting</a></li>
						<li><a href="training">Training</a></li>

					</ul>
				</section>
				<section class="6u 12u(narrower)">
					<h3>Get In Touch</h3>
					<form name="form1" method="post" action="process.asp">
						<div class="row 50%">
							<div class="6u 12u(mobilep)">
								<input type="text" name="name" id="name" placeholder="Name" />
							</div>
							<div class="6u 12u(mobilep)">
								<input type="email" name="email" id="email" placeholder="Email" />
							</div>
						</div>
						<div class="row 50%">
							<div class="12u">
								<textarea name="message" id="message" placeholder="Message" rows="5"></textarea>
							</div>
						</div>
						<div class="row 50%">
							<div class="12u">
								<ul class="actions">
									<li><input type="submit" class="button alt" value="Send Message" /></li>
								</ul>
							</div>
						</div>
					</form>
				</section>
			</div>
		</div>

	<!-- Icons -->
			<ul class="icons">
				<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
				<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
				<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
				<li><a href="#" class="icon fa-linkedin"><span class="label">LinkedIn</span></a></li>
				<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
			</ul>
	<!-- Copyright -->
			<div class="copyright">
			<ul class="menu">
				<li>&copy; Arcane LLC. All rights reserved</li>
			</ul>
			</div>
		</div>
	</div>