<!-- Header -->
	<div id="header">

	<!-- Logo -->
		<h1><a href="#" id="logo"><img src="images/arcanelg.png" height="30%" width="30%"/>  </a></h1>

		<!-- Nav -->
			<nav id="nav">
			<ul>
				<li class="current"><a href="index.html">Home</a></li>
				<li><a href="mission.html">Our Mission</a></li>
				<li><a href="#">Services</a>
				<ul>
					<li><a href="compliance.html">Compliance</a></li>
					<li><a href="regulatory-audit.html">Auditing</a></li>
					<li><a href="reporting.html">Reporting</a></li>
					<li><a href="vendor-assessment.html">Assessment</a></li>
					<li><a href="training.html">Training</a></li>
				</ul>
				</li>
				<li><a href="contact.html">Contact</a></li>
			</ul>
			</nav>

	</div>